### PR TITLE
Added update method

### PR DESCRIPTION
**Pull request by mocanuga**
This method allows updating the sparkline with a new dataset but with the same options

### CODE REVIEW

**Comment by mariusGundersen** [comment]
Not sure why this method is needed, since the `draw(points)` method already does this?

**Comment by mocanuga** [comment]
Now i don't need to recreate the canavas. I just update it. I implemented a ticker to update it regularly and it seemed the way to go for me.

**Comment by mariusGundersen** [comment]
hmm, which browser are you seeing this in? Setting the width/height of the canvas should reset the context and clear the screen, and the height is being set in the `draw()` method so there is no need to call clearRect before calling `draw()`. 

You can see an example of this [here](https://lab.mariusgundersen.net/sparklines/), where there is a `mousemove` listener that continously redraws the sparkline.

**Comment by mocanuga** [comment]
I noticed this in Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by mariusGundersen** [comment]
I'm not seeing that issue on [this page](https://lab.mariusgundersen.net/sparklines/) in that browser. Do you see the issue there?

**Comment by mocanuga** [comment]
I commented the lines that updated the canvas size and was unaware of this side effect.
Thanks for the script.

**Pull request closed without merging**
